# To run: conda env create -f environment.yml
name: metcnn
channels:
    - conda-forge
    - nvidia
    - pytorch
dependencies:
    # - python=3.7
    # - cudatoolkit=10.0
    - itk==5.2.0
    - lazy_import
    - matplotlib
    - numba
    - numpy
    - PyYAML
    - scikit-image
    - SimpleITK==2.2.1
    - pytorch::pytorch==1.10.2
    - pytorch::torchvision
    - tqdm